name: iso_build
on:
  workflow_dispatch:
  schedule:
    - cron:  '30 2 * * *'

jobs:
  prepare_release:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - 
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YYYYMMDDHHmm'
      - 
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.time.outputs.time }}
          release_name: Release ${{ steps.time.outputs.time }}
          draft: false
          prerelease: false
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
      release_id: ${{ steps.release.outputs.id }}

  release:
    runs-on: ubuntu-20.04
    needs: prepare_release    
    strategy:
      matrix:
        EDITION: [manjaro-kde-desktop]
    steps:
      - 
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - 
        name: build
        env:
          EDITION: ${{ matrix.EDITION }}
        run: |  
          sudo git clone https://github.com/philmmanjaro/linux-scripts.git
          ls
          cd linux-scripts
          sudo ./build_image.sh $EDITION
          FILE_PATH=$(find . -type f -name "*.qcow2" -exec stat -c '%Y %n' {} \; | sort -nr | awk 'NR==1 {print $2}')   
      - 
        name: rollback_release
        if: failure()
        uses: author/action-rollback@stable
        with:
          release_id: ${{ needs.prepare_release.outputs.release_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
